-- MySQL Script generated by MySQL Workbench
-- Sat Nov 16 10:57:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ccinfom_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ccinfom_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ccinfom_db` ;
USE `ccinfom_db` ;

-- -----------------------------------------------------
-- Table `ccinfom_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `display_name` VARCHAR(45) NOT NULL,
  `balance` DECIMAL(8,2) NOT NULL DEFAULT 200.00,
  `user_type` ENUM('basic', 'admin') NOT NULL DEFAULT 'basic',
  `password_hash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`sessions` (
  `id` VARCHAR(128) NOT NULL,
  `user` INT NOT NULL,
  `expiry` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `user_FK_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `sessions_user_FK`
    FOREIGN KEY (`user`)
    REFERENCES `ccinfom_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `game` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `gameFK_idx` (`game` ASC) VISIBLE,
  CONSTRAINT `items_gameFK`
    FOREIGN KEY (`game`)
    REFERENCES `ccinfom_db`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`listings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` INT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `seller` INT NOT NULL,
  `list_date` DATETIME NOT NULL DEFAULT NOW(),
  `sold` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `itemFK_idx` (`item` ASC) VISIBLE,
  INDEX `sellerFK_idx` (`seller` ASC) VISIBLE,
  CONSTRAINT `listings_itemFK`
    FOREIGN KEY (`item`)
    REFERENCES `ccinfom_db`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `listings_sellerFK`
    FOREIGN KEY (`seller`)
    REFERENCES `ccinfom_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`inventory_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`inventory_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` INT NOT NULL,
  `user` INT NOT NULL,
  `obtained_on` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `itemFK_idx` (`item` ASC) VISIBLE,
  INDEX `userFK_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `inventoryItems_itemFK`
    FOREIGN KEY (`item`)
    REFERENCES `ccinfom_db`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `inventoryItems_userFK`
    FOREIGN KEY (`user`)
    REFERENCES `ccinfom_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`sold_listings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`sold_listings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing` INT NOT NULL,
  `buyer` INT NOT NULL,
  `buy_date` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `listingFK_idx` (`listing` ASC) VISIBLE,
  INDEX `buyerFK_idx` (`buyer` ASC) VISIBLE,
  CONSTRAINT `soldlistings_listingFK`
    FOREIGN KEY (`listing`)
    REFERENCES `ccinfom_db`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `soldlistings_buyerFK`
    FOREIGN KEY (`buyer`)
    REFERENCES `ccinfom_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`past_inventory_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`past_inventory_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` INT NOT NULL,
  `user` INT NOT NULL,
  `lost_on` DATETIME NOT NULL DEFAULT  NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `itemFK_idx` (`item` ASC) VISIBLE,
  INDEX `userFK_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `pastitems_itemFK`
    FOREIGN KEY (`item`)
    REFERENCES `ccinfom_db`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pastitems_userFK`
    FOREIGN KEY (`user`)
    REFERENCES `ccinfom_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ccinfom_db`.`login_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ccinfom_db`.`login_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `session` VARCHAR(128) NOT NULL,
  `login_on` DATETIME NOT NULL DEFAULT NOW(),
  `browser` VARCHAR(45) NOT NULL,
  `platform` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `login_history_sessionFK_idx` (`session` ASC) VISIBLE,
  CONSTRAINT `login_history_sessionFK`
    FOREIGN KEY (`session`)
    REFERENCES `ccinfom_db`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
